name: Fort CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ${{ matrix.os }}
    timeout-minutes: 8
    strategy:
      matrix:
        ghc: ['9.8.1', '9.8.2']
        cabal: ['3.10.2.1']
        os: [windows-latest]
        exclude:
          - ghc: 9.8.1
            os: ubuntu-latest
          - ghc: 9.8.1
            os: windows-latest
          - ghc: 9.8.2
            os: macos-latest
    env:
      CONFIG: "--enable-tests --enable-benchmarks"

    steps:
      - uses: actions/checkout@v3
      - uses: haskell-actions/setup@v2
        id: setup-haskell-cabal
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
      - run: cabal update
      - run: cabal freeze $CONFIG
      - uses: actions/cache@v2
        with:
          path: |
            ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
            dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.ghc }}-
      - run: cabal build $CONFIG
      - run: cabal run fort -- examples/helloworld.fort --run
      # - run: cabal test $CONFIG
      # - run: run-examples.sh
